### ISSUE TITLE
Dll error

### ISSUE THREAD

**Issue by aryanrq6222** [githubharald/WordDetector#11]
I am getting this error while running python main.py

Traceback (most recent call last):
  File "C:\Users\ELCOT\Downloads\WordDetector-master\examples\main.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python312\Lib\site-packages\matplotlib\__init__.py", line 272, in <module>
    _check_versions()
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python312\Lib\site-packages\matplotlib\__init__.py", line 266, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python312\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: The specified module could not be found.

**Comment by githubharald** [comment]
this is not related with the repo, but with your local python installation.
